repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
        language_version: python3
    -   id: end-of-file-fixer
        files: ^tf|-|\.(py|env|yml|yaml|pem|key|mock)$
    -   id: detect-private-key
        files: ^(?!\.?git-crypt)
    -   id: check-merge-conflict
        files: ^tf|-|\.(py|tfvars|tf|tfenv|env|yml|yaml|pem|key|mock)$
    -   id: check-added-large-files
        files: ^tf|-|\.(py|env|yml|yaml)$
    -   id: check-case-conflict
    -   id: check-json
        language_version: python3
    -   id: check-xml
        language_version: python3
    -   id: check-yaml
        language_version: python3
    -   id: check-case-conflict
    -   id: check-ast
        language_version: python3
    -   id: double-quote-string-fixer
    -   id: check-docstring-first
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: name-tests-test
        args:
        - --django
    -   id: file-contents-sorter
    -   id: fix-encoding-pragma
    -   id: sort-simple-yaml
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.1
    hooks:
    -   id: flake8
        files: ^src/.*\.py$
        args:
        - --max-line-length=80
        - --diff
        - --exclude=docs,migrations
-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.7.4
    hooks:
    -   id: pylint
        exclude: backend/apps/.*\/migrations/.*\.py$
        args:
        - --rcfile=backend/.pylintrc
        - --errors-only
        - --disable=no-name-in-module,import-error
        - --ignore=migrations
-   repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.1
    hooks:
    -   id: python-safety-dependencies-check
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    -   id: autopep8
        args:
        - -i
        - --ignore=E501
        language_version: python3
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
        args:
        - --no-strict-optional
        - --ignore-missing-imports
